name: Eventd CI / CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install DFX
              run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
            - run: dfx start --no-artificial-delay --clean --background
            - name: Add DFX identity and wallets
              run: ./scripts/add-ic-identity.sh
              env:
                  DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
                  DFX_WALLETS: ${{ secrets.DFX_WALLETS }}
            - name: Download vessel package management
              run: curl -L -o /usr/local/bin/vessel https://github.com/dfinity/vessel/releases/download/v0.6.2/vessel-linux64
            - run: chmod +x /usr/local/bin/vessel
            - name: Build canisters
              run: dfx deploy
            - name: Run tests
              run: ./run-test.sh
            - name: Stop DFX server
              run: dfx stop
            - name: Show success mesg
              run: echo Congratulations! All tests passed successfully.
